import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";

//Changing font throughout for application
const outfitFont = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "eCom Multiplex",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Header />
      <body className={outfitFont.className}>{children}</body>
    </html>
  );
}
